version: "3.9"

services:

  proxy:
    build: ./proxy
    image: chat-proxy
    networks:
      - chatnet
    restart: unless-stopped

  server:
    build: ./server
    image: chat-server
    ports:
      - "5555:5555"
    networks:
      - chatnet
    depends_on:
      - proxy
    volumes:
      - ./server/data:/app/data        # <-- garante salvamento de users/channels/logs
    restart: unless-stopped

  bot_auto:
    build: ./bot
    image: chat-bot
    networks:
      - chatnet
    depends_on:
      - server
      - proxy
    restart: unless-stopped

  client:
    build: ./client
    image: chat-client
    networks:
      - chatnet
    depends_on:
      - server
      - proxy
    stdin_open: true
    tty: true
    restart: unless-stopped

networks:
  chatnet:
    driver: bridge